HISTSIZE=5000
HISTFILE=${XDG_CACHE_HOME:-$HOME/.cache}/.zhistory
SAVEHIST=5000
HISTDUP=erase
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS